/**
 * AI-Based Landslide Risk Monitoring System
 * Core Dataset & GeoJSON Structures
 */

const LANDSLIDE_APP_DATA = {
  systemInfo: {
    title: "AI-Based Early Warning & Landslide Risk Monitoring System",
    version: "2.4.0",
    engine: "Google Earth Engine & PyTorch Ensemble",
    lastRefreshed: new Date().toLocaleTimeString(),
    demoMode: true,
    region: "Western Ghats & Himalayan Pilot Sectors (Tamil Nadu, Kerala, Uttarakhand, HP)"
  },

  // Global Monitored Locations with comprehensive geo-environmental parameters
  locations: [
    // --- India & Himalayas ---
    {
      id: "LOC-01",
      name: "Emerald Valley & Doddabetta Slopes",
      village: "Emerald Village",
      district: "Nilgiris",
      state: "Tamil Nadu, India",
      region: "South Asia",
      lat: 11.3912,
      lng: 76.7112,
      elevation_m: 2180,
      slope_deg: 36.5,
      soil_type: "Lateritic Red Loam",
      geology: "Fissured Charnockite / Hornblende-Biotite Gneiss",
      vegetation_ndvi: 0.58,
      population_density: 420,
      rainfall_24h_mm: 148.5,
      rainfall_7d_mm: 385.0,
      soil_moisture_pct: 82.4,
      pore_pressure_kpa: 46.2,
      temperature_c: 17.2,
      humidity_pct: 94,
      ground_vibration_mms: 0.18,
      historical_incidents: 14,
      risk_probability: 78.6,
      risk_category: "HIGH",
      color: "#ef4444",
      last_updated: "2 mins ago"
    },
    {
      id: "LOC-02",
      name: "Coonoor Ghat Corridor (NH-67)",
      village: "Marapalam Settlement",
      district: "Nilgiris",
      state: "Tamil Nadu, India",
      region: "South Asia",
      lat: 11.3530,
      lng: 76.7959,
      elevation_m: 1850,
      slope_deg: 39.0,
      soil_type: "Clayey Gneiss Regolith",
      geology: "Highly Weathered Quartz-Feldspathic Gneiss",
      vegetation_ndvi: 0.42,
      population_density: 310,
      rainfall_24h_mm: 162.0,
      rainfall_7d_mm: 412.0,
      soil_moisture_pct: 88.0,
      pore_pressure_kpa: 58.6,
      temperature_c: 19.1,
      humidity_pct: 96,
      ground_vibration_mms: 0.42,
      historical_incidents: 22,
      risk_probability: 87.2,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "Just now"
    },
    {
      id: "LOC-03",
      name: "Meppadi - Chooralmala Ridge",
      village: "Chooralmala",
      district: "Wayanad",
      state: "Kerala, India",
      region: "South Asia",
      lat: 11.5432,
      lng: 76.1245,
      elevation_m: 1240,
      slope_deg: 41.2,
      soil_type: "Porous Forest Loam over Granulite",
      geology: "Sheared Granulite Belt with Quartz Intrusions",
      vegetation_ndvi: 0.65,
      population_density: 280,
      rainfall_24h_mm: 210.0,
      rainfall_7d_mm: 520.0,
      soil_moisture_pct: 91.5,
      pore_pressure_kpa: 64.8,
      temperature_c: 21.0,
      humidity_pct: 98,
      ground_vibration_mms: 0.68,
      historical_incidents: 19,
      risk_probability: 92.4,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "1 min ago"
    },
    {
      id: "LOC-04",
      name: "Kotagiri Tea Terraces",
      village: "Kotagiri Rural",
      district: "Nilgiris",
      state: "Tamil Nadu, India",
      region: "South Asia",
      lat: 11.4200,
      lng: 76.8600,
      elevation_m: 1793,
      slope_deg: 24.5,
      soil_type: "Humic Mountain Soil",
      geology: "Moderately Weathered Charnockite",
      vegetation_ndvi: 0.72,
      population_density: 380,
      rainfall_24h_mm: 64.0,
      rainfall_7d_mm: 140.0,
      soil_moisture_pct: 54.0,
      pore_pressure_kpa: 22.0,
      temperature_c: 18.5,
      humidity_pct: 78,
      ground_vibration_mms: 0.05,
      historical_incidents: 6,
      risk_probability: 44.8,
      risk_category: "MODERATE",
      color: "#f59e0b",
      last_updated: "8 mins ago"
    },
    {
      id: "LOC-05",
      name: "Munnar Gap Road Pass",
      village: "Devikulam Sector",
      district: "Idukki",
      state: "Kerala, India",
      region: "South Asia",
      lat: 10.0889,
      lng: 77.0595,
      elevation_m: 1530,
      slope_deg: 34.0,
      soil_type: "Fissured Charnockite Rock/Soil",
      geology: "Jointed Gneissic Escarpment",
      vegetation_ndvi: 0.51,
      population_density: 220,
      rainfall_24h_mm: 98.0,
      rainfall_7d_mm: 245.0,
      soil_moisture_pct: 71.2,
      pore_pressure_kpa: 38.0,
      temperature_c: 16.8,
      humidity_pct: 89,
      ground_vibration_mms: 0.22,
      historical_incidents: 11,
      risk_probability: 64.1,
      risk_category: "HIGH",
      color: "#ef4444",
      last_updated: "5 mins ago"
    },
    {
      id: "LOC-06",
      name: "Kodaikanal Ghat Section",
      village: "Pannaikadu",
      district: "Dindigul",
      state: "Tamil Nadu, India",
      region: "South Asia",
      lat: 10.2381,
      lng: 77.4892,
      elevation_m: 1420,
      slope_deg: 22.0,
      soil_type: "Sandy Clay Loam",
      geology: "Granite Gneiss Massive",
      vegetation_ndvi: 0.61,
      population_density: 340,
      rainfall_24h_mm: 28.0,
      rainfall_7d_mm: 72.0,
      soil_moisture_pct: 36.5,
      pore_pressure_kpa: 14.5,
      temperature_c: 20.4,
      humidity_pct: 65,
      ground_vibration_mms: 0.02,
      historical_incidents: 4,
      risk_probability: 24.2,
      risk_category: "LOW",
      color: "#10b981",
      last_updated: "15 mins ago"
    },
    {
      id: "LOC-07",
      name: "Chamoli Valley Himalayan Flank",
      village: "Joshimath Sector B",
      district: "Chamoli",
      state: "Uttarakhand, India",
      region: "Himalayas",
      lat: 30.5564,
      lng: 79.5667,
      elevation_m: 1890,
      slope_deg: 38.0,
      soil_type: "Glacial Moraine Till",
      geology: "Central Crystallines (Schist, Quartzite)",
      vegetation_ndvi: 0.38,
      population_density: 190,
      rainfall_24h_mm: 135.0,
      rainfall_7d_mm: 310.0,
      soil_moisture_pct: 84.0,
      pore_pressure_kpa: 52.0,
      temperature_c: 11.2,
      humidity_pct: 91,
      ground_vibration_mms: 0.35,
      historical_incidents: 26,
      risk_probability: 82.5,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "10 mins ago"
    },
    {
      id: "LOC-08",
      name: "Shimla Bypass Ridge",
      village: "Dhalli Outskirts",
      district: "Shimla",
      state: "Himachal Pradesh, India",
      region: "Himalayas",
      lat: 31.1048,
      lng: 77.1734,
      elevation_m: 2205,
      slope_deg: 29.5,
      soil_type: "Phyllite & Schist Debris",
      geology: "Jutogh Group Metasediments",
      vegetation_ndvi: 0.55,
      population_density: 510,
      rainfall_24h_mm: 45.0,
      rainfall_7d_mm: 98.0,
      soil_moisture_pct: 48.0,
      pore_pressure_kpa: 19.5,
      temperature_c: 14.0,
      humidity_pct: 72,
      ground_vibration_mms: 0.04,
      historical_incidents: 8,
      risk_probability: 38.4,
      risk_category: "MODERATE",
      color: "#f59e0b",
      last_updated: "18 mins ago"
    },
    {
      id: "LOC-09",
      name: "Darjeeling Tea Slopes (Paglajhora)",
      village: "Kurseong Sector",
      district: "Darjeeling",
      state: "West Bengal, India",
      region: "Eastern Himalayas",
      lat: 26.9048,
      lng: 88.2721,
      elevation_m: 1450,
      slope_deg: 37.0,
      soil_type: "Silty Phyllite Regolith",
      geology: "Daling Series Metamorphics",
      vegetation_ndvi: 0.62,
      population_density: 390,
      rainfall_24h_mm: 178.0,
      rainfall_7d_mm: 460.0,
      soil_moisture_pct: 89.2,
      pore_pressure_kpa: 61.4,
      temperature_c: 16.5,
      humidity_pct: 95,
      ground_vibration_mms: 0.45,
      historical_incidents: 31,
      risk_probability: 89.5,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "4 mins ago"
    },

    // --- East & Southeast Asia (Pacific Ring of Fire) ---
    {
      id: "LOC-10",
      name: "Shizuoka Coastal Ridge (Tokaido Corridor)",
      village: "Yui Mountain Pass",
      district: "Shizuoka Prefecture",
      state: "Japan",
      region: "East Asia",
      lat: 35.1054,
      lng: 138.5612,
      elevation_m: 820,
      slope_deg: 38.5,
      soil_type: "Volcanic Tephra & Pyroclastic Ash",
      geology: "Neogene Sedimentary Fault Zone",
      vegetation_ndvi: 0.68,
      population_density: 640,
      rainfall_24h_mm: 168.0,
      rainfall_7d_mm: 390.0,
      soil_moisture_pct: 86.5,
      pore_pressure_kpa: 56.0,
      temperature_c: 18.0,
      humidity_pct: 92,
      ground_vibration_mms: 0.52,
      historical_incidents: 28,
      risk_probability: 86.8,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "3 mins ago"
    },
    {
      id: "LOC-11",
      name: "Benguet Mountain Terraces",
      village: "Itogon Mining Sector",
      district: "Cordillera Region",
      state: "Philippines",
      region: "Southeast Asia",
      lat: 16.3667,
      lng: 120.6667,
      elevation_m: 1300,
      slope_deg: 42.0,
      soil_type: "Weathered Andesite Regolith",
      geology: "Klondyke Clastic Formation",
      vegetation_ndvi: 0.52,
      population_density: 310,
      rainfall_24h_mm: 225.0,
      rainfall_7d_mm: 580.0,
      soil_moisture_pct: 94.0,
      pore_pressure_kpa: 68.2,
      temperature_c: 22.4,
      humidity_pct: 99,
      ground_vibration_mms: 0.74,
      historical_incidents: 35,
      risk_probability: 95.2,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "Just now"
    },
    {
      id: "LOC-12",
      name: "Cianjur Volcanic Escarpment",
      village: "Cugenang Valley",
      district: "West Java",
      state: "Indonesia",
      region: "Southeast Asia",
      lat: -6.8167,
      lng: 107.1333,
      elevation_m: 950,
      slope_deg: 35.0,
      soil_type: "Andosol / Pyroclastic Clay",
      geology: "Gede-Pangrango Volcanic Deposits",
      vegetation_ndvi: 0.70,
      population_density: 580,
      rainfall_24h_mm: 140.0,
      rainfall_7d_mm: 310.0,
      soil_moisture_pct: 83.0,
      pore_pressure_kpa: 48.5,
      temperature_c: 24.1,
      humidity_pct: 91,
      ground_vibration_mms: 0.38,
      historical_incidents: 24,
      risk_probability: 79.4,
      risk_category: "HIGH",
      color: "#ef4444",
      last_updated: "12 mins ago"
    },

    // --- Europe (Alps & Mediterranean) ---
    {
      id: "LOC-13",
      name: "Brienz Rockfall & Mudflow Zone",
      village: "Brienz / Brinzauls",
      district: "Graubünden Canton",
      state: "Switzerland",
      region: "European Alps",
      lat: 46.6917,
      lng: 9.6917,
      elevation_m: 1140,
      slope_deg: 44.0,
      soil_type: "Calcareous Scree / Talus",
      geology: "Fractured Flysch & Dolomite",
      vegetation_ndvi: 0.45,
      population_density: 85,
      rainfall_24h_mm: 88.0,
      rainfall_7d_mm: 210.0,
      soil_moisture_pct: 76.0,
      pore_pressure_kpa: 42.0,
      temperature_c: 8.5,
      humidity_pct: 82,
      ground_vibration_mms: 0.88,
      historical_incidents: 18,
      risk_probability: 84.1,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "7 mins ago"
    },
    {
      id: "LOC-14",
      name: "Amalfi Coastal Cliff Route",
      village: "Positano Sector",
      district: "Campania",
      state: "Italy",
      region: "Southern Europe",
      lat: 40.6281,
      lng: 14.4850,
      elevation_m: 420,
      slope_deg: 46.0,
      soil_type: "Karstified Limestone Rubble",
      geology: "Mesozoic Carbonate Platform",
      vegetation_ndvi: 0.48,
      population_density: 420,
      rainfall_24h_mm: 72.0,
      rainfall_7d_mm: 165.0,
      soil_moisture_pct: 62.0,
      pore_pressure_kpa: 28.0,
      temperature_c: 19.5,
      humidity_pct: 75,
      ground_vibration_mms: 0.15,
      historical_incidents: 12,
      risk_probability: 58.6,
      risk_category: "MODERATE",
      color: "#f59e0b",
      last_updated: "25 mins ago"
    },

    // --- North America (Cascades & Coastal Ranges) ---
    {
      id: "LOC-15",
      name: "North Fork Stillaguamish Corridor (Oso Sector)",
      village: "Snohomish County",
      district: "Washington State",
      state: "USA",
      region: "North America",
      lat: 48.2831,
      lng: -121.9167,
      elevation_m: 320,
      slope_deg: 36.0,
      soil_type: "Glaciolacustrine Silt & Clay",
      geology: "Unconsolidated Quaternary Sediments",
      vegetation_ndvi: 0.74,
      population_density: 45,
      rainfall_24h_mm: 112.0,
      rainfall_7d_mm: 290.0,
      soil_moisture_pct: 85.0,
      pore_pressure_kpa: 54.2,
      temperature_c: 12.0,
      humidity_pct: 90,
      ground_vibration_mms: 0.29,
      historical_incidents: 16,
      risk_probability: 77.8,
      risk_category: "HIGH",
      color: "#ef4444",
      last_updated: "14 mins ago"
    },
    {
      id: "LOC-16",
      name: "Big Sur Coastal Highway Slip",
      village: "Paul's Slide Sector",
      district: "Monterey County",
      state: "California, USA",
      region: "North America",
      lat: 35.9867,
      lng: -121.4933,
      elevation_m: 480,
      slope_deg: 40.0,
      soil_type: "Franciscan Mélange & Serpentine",
      geology: "Sheared Metavolcanic Complex",
      vegetation_ndvi: 0.38,
      population_density: 20,
      rainfall_24h_mm: 82.0,
      rainfall_7d_mm: 195.0,
      soil_moisture_pct: 68.0,
      pore_pressure_kpa: 34.0,
      temperature_c: 16.2,
      humidity_pct: 78,
      ground_vibration_mms: 0.21,
      historical_incidents: 20,
      risk_probability: 63.4,
      risk_category: "HIGH",
      color: "#ef4444",
      last_updated: "19 mins ago"
    },

    // --- South America (Andes Mountain Range) ---
    {
      id: "LOC-17",
      name: "Mocoa River Debris Flow Catchment",
      village: "Tarqui & San Miguel",
      district: "Putumayo Department",
      state: "Colombia",
      region: "South American Andes",
      lat: 1.1481,
      lng: -76.6492,
      elevation_m: 604,
      slope_deg: 39.0,
      soil_type: "Granitic Saprolite & Boulders",
      geology: "Eastern Cordillera Plutonic Basement",
      vegetation_ndvi: 0.65,
      population_density: 240,
      rainfall_24h_mm: 195.0,
      rainfall_7d_mm: 480.0,
      soil_moisture_pct: 92.0,
      pore_pressure_kpa: 62.5,
      temperature_c: 23.0,
      humidity_pct: 96,
      ground_vibration_mms: 0.62,
      historical_incidents: 25,
      risk_probability: 91.8,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "5 mins ago"
    },
    {
      id: "LOC-18",
      name: "Yungay Cordillera Blanca Slope",
      village: "Huascaran Sector",
      district: "Ancash Region",
      state: "Peru",
      region: "South American Andes",
      lat: -9.1417,
      lng: -77.7417,
      elevation_m: 2500,
      slope_deg: 43.0,
      soil_type: "Glacial Till & Moraine Debris",
      geology: "Granodiorite Batholith",
      vegetation_ndvi: 0.32,
      population_density: 110,
      rainfall_24h_mm: 95.0,
      rainfall_7d_mm: 220.0,
      soil_moisture_pct: 74.0,
      pore_pressure_kpa: 44.0,
      temperature_c: 10.5,
      humidity_pct: 84,
      ground_vibration_mms: 0.48,
      historical_incidents: 15,
      risk_probability: 81.2,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "11 mins ago"
    },

    // --- Oceania (Southern Alps & Pacific Islands) ---
    {
      id: "LOC-19",
      name: "Kaikoura Coastal Fault Ranges",
      village: "Halfway Bay Sector",
      district: "Canterbury",
      state: "New Zealand",
      region: "Oceania",
      lat: -42.4000,
      lng: 173.6833,
      elevation_m: 910,
      slope_deg: 41.0,
      soil_type: "Torlesse Greywacke Scree",
      geology: "Active Plate Boundary Strike-Slip",
      vegetation_ndvi: 0.54,
      population_density: 35,
      rainfall_24h_mm: 85.0,
      rainfall_7d_mm: 190.0,
      soil_moisture_pct: 69.0,
      pore_pressure_kpa: 36.0,
      temperature_c: 13.5,
      humidity_pct: 79,
      ground_vibration_mms: 0.58,
      historical_incidents: 27,
      risk_probability: 72.4,
      risk_category: "HIGH",
      color: "#ef4444",
      last_updated: "22 mins ago"
    },
    {
      id: "LOC-20",
      name: "Enga Province Highlands Flank",
      village: "Yambali Settlement",
      district: "Enga Province",
      state: "Papua New Guinea",
      region: "Oceania",
      lat: -5.3833,
      lng: 143.5167,
      elevation_m: 2150,
      slope_deg: 45.0,
      soil_type: "Porous Volcanic Ash over Limestone",
      geology: "Fold & Thrust Belt Metasediments",
      vegetation_ndvi: 0.76,
      population_density: 160,
      rainfall_24h_mm: 205.0,
      rainfall_7d_mm: 510.0,
      soil_moisture_pct: 93.5,
      pore_pressure_kpa: 66.0,
      temperature_c: 17.5,
      humidity_pct: 97,
      ground_vibration_mms: 0.69,
      historical_incidents: 21,
      risk_probability: 93.6,
      risk_category: "CRITICAL",
      color: "#991b1b",
      last_updated: "6 mins ago"
    }
  ],

  // Global Risk Polygons for GIS visual hazard extents
  riskPolygons: [
    {
      name: "Nilgiris High Hazard Zone Alpha (India)",
      risk_category: "CRITICAL",
      coords: [
        [11.38, 76.70],
        [11.41, 76.72],
        [11.39, 76.81],
        [11.33, 76.78],
        [11.34, 76.69]
      ]
    },
    {
      name: "Wayanad Escarpment Red Polygon (India)",
      risk_category: "CRITICAL",
      coords: [
        [11.52, 76.10],
        [11.56, 76.11],
        [11.55, 76.15],
        [11.51, 76.14]
      ]
    },
    {
      name: "Brienz Alpine Rockfall Sector (Switzerland)",
      risk_category: "CRITICAL",
      coords: [
        [46.68, 9.67],
        [46.71, 9.69],
        [46.70, 9.72],
        [46.67, 9.70]
      ]
    },
    {
      name: "Benguet Itogon Mining Slope (Philippines)",
      risk_category: "CRITICAL",
      coords: [
        [16.35, 120.64],
        [16.38, 120.66],
        [16.37, 120.69],
        [16.34, 120.67]
      ]
    },
    {
      name: "Mocoa River Basin Debris Zone (Colombia)",
      risk_category: "CRITICAL",
      coords: [
        [1.13, -76.67],
        [1.17, -76.65],
        [1.16, -76.62],
        [1.12, -76.64]
      ]
    },
    {
      name: "Enga Highlands Slide Zone (Papua New Guinea)",
      risk_category: "CRITICAL",
      coords: [
        [-5.40, 143.49],
        [-5.36, 143.51],
        [-5.37, 143.54],
        [-5.41, 143.52]
      ]
    }
  ],

  // Early Warning Alerts
  alerts: [
    {
      id: "ALT-2026-091",
      location_id: "LOC-03",
      location_name: "Chooralmala, Meppadi Ridge (Wayanad)",
      district: "Wayanad",
      alert_level: "CRITICAL",
      risk_probability_pct: 92.4,
      headline: "CRITICAL RED ALERT: Imminent Debris Flow & Landslide Hazard",
      trigger_reason: "Cumulative 24h precipitation (210 mm) triggered extreme soil saturation (91.5%) on 41.2° steep slope.",
      recommended_action: "Immediate evacuation of downslope settlements. Close valley route traffic and mobilize NDRF/SDRF teams.",
      status: "CRITICAL",
      timestamp: "10 mins ago"
    },
    {
      id: "ALT-2026-088",
      location_id: "LOC-02",
      location_name: "Coonoor Ghat Corridor (NH-67)",
      district: "Nilgiris",
      alert_level: "HIGH RISK",
      risk_probability_pct: 87.2,
      headline: "HIGH RISK WARNING: Road Cut Slumping & Rockfall Vulnerability",
      trigger_reason: "Persistent rain (162 mm) causing lateral soil thrust and seepage on 39° slope.",
      recommended_action: "Restrict heavy vehicular movement on NH-67 Ghat section. Deploy geotechnical highway inspection teams.",
      status: "ACTIVE",
      timestamp: "25 mins ago"
    },
    {
      id: "ALT-2026-085",
      location_id: "LOC-01",
      location_name: "Emerald Valley & Doddabetta Slopes",
      district: "Nilgiris",
      alert_level: "HIGH RISK",
      risk_probability_pct: 78.6,
      headline: "HIGH RISK WATCH: Soil Creep & Drainage Overflow Detected",
      trigger_reason: "Soil moisture at 82.4% with continuing rainfall bands forecast over Doddabetta catchment.",
      recommended_action: "Clear culverts, inspect retaining walls, and alert local village panchayat emergency monitors.",
      status: "ACTIVE",
      timestamp: "45 mins ago"
    },
    {
      id: "ALT-2026-082",
      location_id: "LOC-05",
      location_name: "Munnar Gap Road Pass",
      district: "Idukki",
      alert_level: "WARNING",
      risk_probability_pct: 64.1,
      headline: "WARNING: Potential Rock Displacement along Cliff Face",
      trigger_reason: "Rainfall reaching 98mm on fractured rocky terrain with high joints density.",
      recommended_action: "Erect cautionary warning signage, speed reduction limits, and monitor rockfall mesh netting.",
      status: "ACTIVE",
      timestamp: "2 hours ago"
    },
    {
      id: "ALT-2026-077",
      location_id: "LOC-04",
      location_name: "Kotagiri Tea Terraces",
      district: "Nilgiris",
      alert_level: "WATCH",
      risk_probability_pct: 44.8,
      headline: "WATCH: Moderate Runoff Flow on Agricultural Terraces",
      trigger_reason: "Localized showers with moderate soil dampening.",
      recommended_action: "Maintain drainage trenches along boundary paths.",
      status: "RESOLVED",
      timestamp: "6 hours ago"
    }
  ],

  // Citizen Reports
  citizenReports: [
    {
      id: "CIT-8021",
      reporter_name: "R. Vignesh",
      contact_info: "+91 98401 23456",
      location_name: "Marapalam 3rd Hairpin Bend",
      district: "Nilgiris",
      lat: 11.3551,
      lng: 76.7972,
      report_type: "Ground cracks",
      description: "Noticed 3-inch wide tensile ground cracks running parallel across the upper road shoulder after morning downpour.",
      photo_url: "assets/demo_cracks.jpg",
      status: "Verified",
      risk_level: "HIGH",
      timestamp: "35 mins ago"
    },
    {
      id: "CIT-8022",
      reporter_name: "A. Joseph",
      contact_info: "+91 94470 65432",
      location_name: "Chooralmala Tea Estate Block 4",
      district: "Wayanad",
      lat: 11.5410,
      lng: 76.1260,
      report_type: "Soil movement",
      description: "Mud water flowing with gravel down the stream embankment; leaning eucalyptus trees observed on hillcrest.",
      photo_url: "assets/demo_mudflow.jpg",
      status: "Verified",
      risk_level: "CRITICAL",
      timestamp: "1 hour ago"
    },
    {
      id: "CIT-8023",
      reporter_name: "S. Rajeshwari",
      contact_info: "+91 97890 11223",
      location_name: "Kotagiri Valley Edge",
      district: "Nilgiris",
      lat: 11.4230,
      lng: 76.8620,
      report_type: "Water accumulation",
      description: "Drainage ditch blocked with sediment causing heavy runoff pooling on steep terrace boundary.",
      photo_url: "assets/demo_drainage.jpg",
      status: "Under Review",
      risk_level: "MODERATE",
      timestamp: "3 hours ago"
    },
    {
      id: "CIT-8024",
      reporter_name: "K. Mohan Kumar",
      contact_info: "+91 94888 77665",
      location_name: "Ooty - Pykara Road Km 14",
      district: "Nilgiris",
      lat: 11.4510,
      lng: 76.6210,
      report_type: "Rockfall",
      description: "Small boulders dislodged from road cut onto outer lane; traffic partially obstructed.",
      photo_url: "assets/demo_rockfall.jpg",
      status: "Verified",
      risk_level: "HIGH",
      timestamp: "5 hours ago"
    }
  ],

  // Historical Landslide Incidents Inventory (2018 - 2025)
  historicalIncidents: [
    { id: "HIS-01", date: "2024-07-30", location: "Meppadi Chooralmala", district: "Wayanad", severity: "CATASTROPHIC", rain_24h: 382, fatalities: 231, damage: "Entire residential settlement and bridge washed away by massive debris flow" },
    { id: "HIS-02", date: "2024-08-12", location: "Marapalam NH-67", district: "Nilgiris", severity: "SEVERE", rain_24h: 215, fatalities: 0, damage: "Highway breached for 60 meters, road connectivity severed for 5 days" },
    { id: "HIS-03", date: "2023-09-18", location: "Joshimath Sector B", district: "Chamoli", severity: "SEVERE", rain_24h: 175, fatalities: 0, damage: "Subsidence and deep rotational slumps affecting 45 structures" },
    { id: "HIS-04", date: "2022-08-04", location: "Gap Road Devikulam", district: "Idukki", severity: "SEVERE", rain_24h: 198, fatalities: 2, damage: "Rockfall debris crushed construction equipment and retaining wall" },
    { id: "HIS-05", date: "2021-11-10", location: "Emerald Valley", district: "Nilgiris", severity: "MODERATE", rain_24h: 140, fatalities: 0, damage: "Tea plantation terrace failure, 2 agricultural pump sheds buried" },
    { id: "HIS-06", date: "2020-08-07", location: "Pettimudi Rajamala", district: "Idukki", severity: "CATASTROPHIC", rain_24h: 310, fatalities: 66, damage: "Tea estate labour quarters engulfed in nocturnal slope collapse" },
    { id: "HIS-07", date: "2019-08-08", location: "Kavalappara", district: "Malappuram", severity: "CATASTROPHIC", rain_24h: 290, fatalities: 59, damage: "Spontaneous liquefaction flow down hill flank" },
    { id: "HIS-08", date: "2018-08-16", location: "Coonoor Railway Ghat Line", district: "Nilgiris", severity: "MODERATE", rain_24h: 165, fatalities: 0, damage: "UNESCO Heritage Mountain Railway track suspended mid-air due to embankment wash" }
  ],

  // Google Earth Engine & Sensor Subsystem Telemetry Feeds
  dataSources: [
    { name: "Google Earth Engine (GEE)", status: "CONNECTED", type: "Satellite Pipeline", latency: "42 ms", detail: "Sentinel-1 InSAR + SRTM 30m DEM + MODIS/Landsat" },
    { name: "IMD Doppler Radar & AWS Network", status: "CONNECTED", type: "Weather Telemetry", latency: "38 ms", detail: "Real-time precipitation radar & 15-min automated rain gauges" },
    { name: "NASA SMAP & In-Situ TDR Probes", status: "CONNECTED", type: "Soil Moisture", latency: "55 ms", detail: "Topsoil (0-10cm) & Root-zone (10-100cm) volumetric water content" },
    { name: "AI Inference Engine (LS-Ensemble)", status: "CONNECTED", type: "ML Core", latency: "12 ms", detail: "Multi-factor weighted susceptibility + SHAP explanation generator" },
    { name: "GSI Landslide Hazard Database", status: "CONNECTED", type: "Historical DB", latency: "18 ms", detail: "Geological Survey of India historical landslide inventory archive" },
    { name: "CAP Disaster Alerting Gateway", status: "CONNECTED", type: "Public Warning", latency: "25 ms", detail: "Common Alerting Protocol (CAP) SMS, WhatsApp, and Local Sirens" }
  ],

  // System Workflow Stages (Based on reference infographic)
  workflowStages: [
    {
      step: 1,
      title: "Satellite & Geospatial Data",
      subtitle: "Multi-mission Remote Sensing",
      desc: "Ingests real-time earth observation data including Sentinel-1 Synthetic Aperture Radar (InSAR for ground deformation), Sentinel-2 optical imagery (NDVI vegetation index), NASA SRTM DEM (slope & elevation), and NASA GPM precipitation data.",
      tech: "ESA Copernicus, NASA Earthdata, ALOS PALSAR",
      icon: "satellite"
    },
    {
      step: 2,
      title: "Google Earth Engine Integration",
      subtitle: "Cloud-Scale Geospatial Computing",
      desc: "Executes distributed spatial raster transformations, computes topographic relief factors, extracts hydrologic drainage basins, and performs time-series InSAR coherence loss analysis in the cloud without local processing overhead.",
      tech: "Google Earth Engine Python API, Earth Engine Catalog",
      icon: "cloud"
    },
    {
      step: 3,
      title: "Current Environmental Data",
      subtitle: "Real-Time Ground Sensor Telemetry",
      desc: "Streams live telemetry from in-situ automated weather stations (AWS), TDR subsurface soil moisture sensors, vibrating-wire piezometers (pore-water pressure), and borehole tiltmeters deployed across critical slopes.",
      tech: "IMD AWS Network, IoT Sensor Gateways, LoRaWAN",
      icon: "radio"
    },
    {
      step: 4,
      title: "AI / Machine Learning Engine",
      subtitle: "Multi-Factor Landslide Susceptibility Scoring",
      desc: "Processes normalized environmental and geological weights through an ensemble AI model (Random Forest, XGBoost & LSTM) to calculate instant risk probabilities, model confidence scores, and multi-factor impact breakdowns.",
      tech: "PyTorch, Scikit-learn, SHAP Explainability Engine",
      icon: "cpu"
    },
    {
      step: 5,
      title: "Landslide Risk Prediction",
      subtitle: "Dynamic Probability & Trend Forecasting",
      desc: "Classifies risk into standardized color-coded brackets (0-30% Low, 31-60% Moderate, 61-80% High, 81-100% Critical) and forecasts short-term (+6h, +24h) and medium-term (+7d) risk trajectories based on meteorological forecast models.",
      tech: "Susceptibility Indexing, Dynamic Hydrological Modeling",
      icon: "trending-up"
    },
    {
      step: 6,
      title: "Interactive Dynamic Risk Map",
      subtitle: "Geographic Information System (GIS)",
      desc: "Visualizes live hazard zones, radar precipitation overlays, citizen-submitted reports, slope contours, and satellite base layers on an interactive GIS map with real-time inspection panels.",
      tech: "Leaflet GIS, OpenTopoMap, Esri Satellite, GeoJSON",
      icon: "map"
    },
    {
      step: 7,
      title: "Early Warning & Action",
      subtitle: "Targeted Evacuation & Disaster Response",
      desc: "Automatically triggers location-specific alerts (Info, Watch, Warning, High Risk, Critical) with actionable safety protocols dispatched via SMS, sirens, district emergency operation centers (DEOC), and mobile apps.",
      tech: "Common Alerting Protocol (CAP), NDMA / SDMA Gateway",
      icon: "alert-triangle"
    }
  ]
};
